name: TiceIndustries
favicon: null
layout_spectrum: 0.8968
typography_spectrum: 0.46070325071923435
title: Tice Industries Custom Door Hardware
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#142f26'
    - '#c7cecc'
    - '#546d58'
    - '#7c9881'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
